#!/usr/bin/python
#-*-coding:utf-8-*-
import os
from urllib2 import Request, urlopen, URLError, HTTPError

os.system("termux-open-url https://wa.me/+525562322055")

def Space(j):
	i = 0
	while i<=j:
		print " ",
		i+=1
os.system('clear')
def menu():
       print """
            ×××DeadLikado+++++++ DeadLikado×××
\033[92m
\t          AUTOR ==}>\033[90m DeadLikado\033[92m
\t          GitHub ==}>\033[90m /DeadLikado01\33[92m
\t          Facebook ==}>\033[90m /DeadLikado01\033[92m
\t          WhatsApp ==}>\033[90m wa.me/+525562322055\033[0m
                           ..:::::::::..
                      ..:::aad8888888baa:::..
                   .::::d:?88888888888?::8b::::.
                 .:::d8888:?88888888??a888888b:::.
               .:::d8888888a8888888aa8888888888b:::.
              ::::dP::::::::88888888888::::::::Yb::::
             ::::dP:::::::::Y888888888P:::::::::Yb::::
            ::::d8:::::::::::Y8888888P:::::::::::8b::::
           .::::88::::::::::::Y88888P::::::::::::88::::.
           :::::Y8baaaaaaaaaa88P:T:Y88aaaaaaaaaad8P:::::
           :::::::Y88888888888P::|::Y88888888888P:::::::
           ::::::::::::::::888:::|:::888::::::::::::::::
            :::::::::::::::8888888888888b::::::::::::::
            :::::::::::::::88888888888888::::::::::::::
             :::::::::::::d88888888888888:::::::::::::
              ::::::::::::88::88::88:::88::::::::::::
                ::::::::::88::88::88:::88::::::::::
                  ::::::::88::88::P::::88::::::::
                    ::::::88::88:::::::88::::::
                        :::::::::::::::::::
                             :::::::::\033[96;1m
         _   ___  __  __ ___ _  _   ___  _   _  _ ___ _
        /_\ |   \|  \/  |_ _| \| | | _ \/_\ | \| | __| |
       / _ \| |) | |\/| || || .` | |  _/ _ \| .` | _|| |__
      /_/ \_\___/|_|  |_|___|_|\_| |_|/_/ \_\_|\_|___|____|\033[93m
"""
menu()
dl = open("admin.txt","r");
# Admin
url = raw_input("URL ===}>  : ")
print 45* '_'
while True:
	 url_sub = dl.readline()
	 if not url_sub:
		 break
 	 req_url = "http://"+url+"/"+url_sub
   	 req = Request(req_url)
	 try:
	     response = urlopen(req)
	 except HTTPError as e:
		 continue
 	 except URLError as e:
		 continue
	 else:
		 print "\033[92mYES\033[93m ===\033[96;1m}\033[91m>\033[93m ",req_url
